import {
  SiBootstrap,
  SiCss3,
  SiExpress,
  SiHtml5,
  SiLeaflet,
  SiNestjs,
  SiSass,
  SiSupabase,
  SiTailwindcss,
  SiWordpress,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiNodedotjs,
  SiDeno,
  SiPhp,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiPug,
  SiDocker,
  SiSwagger,
  SiOpenapiinitiative,
  SiPostman,
} from "react-icons/si";
import { BsFiletypeXml } from "react-icons/bs";
import { TbDatabaseEdit } from "react-icons/tb";
import { GiThreePointedShuriken } from "react-icons/gi";
import { MdDataObject } from "react-icons/md";
import { FaCcPaypal } from "react-icons/fa6";
import { StackMap } from "../types";

export const stackMap: StackMap = {
  HTML: { name: "HTML", icon: SiHtml5, color: "#f06524", bgColor: "#ffffff" },
  CSS: { name: "CSS", icon: SiCss3 },
  React: { name: "React", icon: SiReact },
  TailwindCSS: { name: "TailwindCSS", icon: SiTailwindcss },
  BootStrap: { name: "BootStrap", icon: SiBootstrap },
  MongoDB: { name: "MongoDB", icon: SiMongodb },
  MySQL: { name: "MySQL", icon: SiMysql },
  PostgreSQL: { name: "PostgreSQL", icon: SiPostgresql },
  NodeJS: { name: "NodeJS", icon: SiNodedotjs },
  Deno: { name: "Deno", icon: SiDeno },
  JavaScript: {
    name: "JavaScript",
    icon: SiJavascript,
    color: "#f6df17",
    bgColor: "#000000",
  },
  TypeScript: { name: "TypeScript", icon: SiTypescript },
  PHP: { name: "PHP", icon: SiPhp },
  XML: { name: "XML", icon: BsFiletypeXml },
  ExpressJS: { name: "ExpressJS", icon: SiExpress },
  Leaflet: { name: "Leaflet", icon: SiLeaflet, color: "#82c041" },
  NestJS: { name: "NestJS", icon: SiNestjs },
  NextJS: { name: "NextJS", icon: SiNestjs },
  SASS: { name: "SASS", icon: SiSass, color: "#cd669b" },
  Supabase: { name: "Supabase", icon: SiSupabase },
  WordPress: { name: "WordPress", icon: SiWordpress },
  PayPal: { name: "PayPal", icon: FaCcPaypal },
  Pug: { name: "Pug", icon: SiPug },
  Docker: { name: "Docker", icon: SiDocker },
  Swagger: { name: "Docker", icon: SiSwagger },
  OpenAPI: { name: "Docker", icon: SiOpenapiinitiative },
  Postman: { name: "Docker", icon: SiPostman },
  CRUD: { name: "CRUD", icon: TbDatabaseEdit },
  MVC: { name: "MVC", icon: GiThreePointedShuriken },
  OOP: { name: "OOP", icon: MdDataObject },
};
